name: Deploy Next.js with Docker

on:
  push:
    branches:
      - main  # Deploy only when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into VPS and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/peeper-app || git clone https://github.com/${{ github.repository_owner }}/peeper-app.git /var/www/peeper-app
          cd /var/www/peeper-app
          git pull origin main
          docker build -t peeper-app .
          docker stop peeper-app || true
          docker rm peeper-app || true
          docker run -d -p 3000:3000 --name peeper-app peeper-app 